[deps]
Blink = "ad839575-38b3-5650-b840-f874b8c74a25"
CSSUtil = "70588ee8-6100-5070-97c1-3cb50ed05fe8"
Codify = "67e8a8f0-3181-11e9-0720-1d07a4d049a5"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
DynamicEnergyBudgets = "6ffd65d2-8b0b-5314-9c5b-6efe83b0316c"
FieldDefaults = "49426c49-986f-5969-8844-d5cc96441cfc"
FieldMetadata = "bf96fef3-21d2-5d20-8afa-0e7d4c32a885"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Flatten = "4c728ea3-d9ee-5c9a-9642-b6f7d7dc04fa"
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
InteractBase = "d3863d7c-f0c8-5437-a7b4-3ae773c01009"
InteractBulma = "7981ab7d-5bfa-5e03-9ec9-f3d4afc0a1ca"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LabelledArrays = "2ee39098-c373-598a-b85f-a56591580800"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
Microclimate = "e0eb800d-4a9f-54ae-b0f8-217228d9d7c3"
Mux = "a975b10e-0019-58db-a62f-e48ff68538c9"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Photosynthesis = "5e10c064-2706-53a3-a67d-d473e313a663"
PlotNested = "d85c2341-301b-47ea-8a8c-4cd93df2bebe"
PlotThemes = "ccf2f8ad-2431-5c83-bf29-c5338b663b6a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
Select = "9af9b3ce-3316-11e9-0fa8-7b2e06453de4"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
SimpleRoots = "6accb78c-d340-5052-9dc3-a835939e19d0"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
TableTraits = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulRecipes = "42071c24-d89e-48dd-8a24-8a12d9b8861f"
WebIO = "0f1e0344-ec1d-5b48-a673-e5cf874b6c29"
